openapi: "3.0.3"

info:
  title: SaladCloud Instance Metadata Service
  contact:
    name: SaladCloud Support
    email: service@salad.com
  termsOfService: https://salad.com/terms
  version: "1.0.0"

servers:
  - url: http://169.254.169.254:80

paths:
  # Instance Metadata
  /v1/status:
    summary: Operations for status
    get:
      summary: Gets the current status for the calling workload instance
      operationId: get_status
      responses:
        "200":
          $ref: "#/components/responses/GetStatus"
        "404":
          $ref: "#/components/responses/404"
        default:
          $ref: "#/components/responses/UnknownError"
  /v1/token:
    summary: Operations for authentication tokens
    get:
      summary: Gets an authentication token for the calling workload instance
      operationId: get_token
      responses:
        "200":
          $ref: "#/components/responses/GetToken"
        "404":
          $ref: "#/components/responses/404"
        default:
          $ref: "#/components/responses/UnknownError"

components:
  responses:
    # Standard Errors
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    UnknownError:
      description: An unknown error occurred
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    # Instance Metadata
    GetStatus:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Status"
    GetToken:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Token"
  schemas:
    # Standard Errors
    ProblemDetails:
      type: object
      description: Represents a problem
      additionalProperties: false
      properties:
        type:
          type: string
          nullable: true
          default: "about:blank"
          description: The URI reference that identifies the problem type
        title:
          type: string
          nullable: true
          description: A short, human-readable summary of the problem type
        status:
          type: integer
          nullable: true
          description: The HTTP status code generated by the origin server
        detail:
          type: string
          nullable: true
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          nullable: true
          description: The URI reference that identifies the specific occurrence of the problem

    # Instance Metadata
    Status:
      type: object
      description: Represents the status of a workload instance
      additionalProperties: false
      required:
        - ready
        - started
      properties:
        ready:
          type: boolean
          description: A value indicating whether the workload is ready
        started:
          type: boolean
          description: A value indicating whether the workload has started
    Token:
      type: object
      description: Represents an authentication token
      additionalProperties: false
      required:
        - jwt
      properties:
        jwt:
          type: string
          description: The authentication token
