blank_issues_enabled: false
contact_links:
  - name: Request support
    url: https://github.com/SaladTechnologies/saladcloud-job-queues-sdk/discussions
    about: Please use GitHub discussions for general chat and community-provided support.
